name: Release to the stores and the web

jobs:
  build_android:
    name: Android
    type: build
    params:
      platform: android
      profile: production

  build_ios:
    name: iOS
    type: build
    params:
      platform: ios
      profile: production

  deploy_web:
    name: Web
    type: deploy
    params:
      prod: true

  submit_android:
    name: Play Store
    needs: [build_android]
    type: submit
    params:
      build_id: ${{ needs.build_android.outputs.build_id }}
      profile: production

  submit_ios:
    name: App Store
    needs: [build_ios]
    type: submit
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
      profile: production
